language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    - develop

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  slack: asearchworkspace:4V3B2DvvLytHrgDaeSNGLxWY

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: foodfeed
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  wait-until-deployed: true
  on:
    repo: ASearchCrew/ASearch-Backend-Boot
    branch: master